export const TypesController = {
    EVA_TEXT_FIELD: "EVA_TEXT_FIELD",
    EVA_NUMBER_FIELD: "EVA_NUMBER_FIELD",
    EVA_CREDIT_CARD_NUMBER_FIELD: "EVA_CREDIT_CARD_NUMBER_FIELD",
    EVA_CHECK_BOX: "EVA_CHECK_BOX",
    EVA_RADIO_GROUP: "EVA_RADIO_GROUP",
}