export const TypesAction = {
    CREATE_SUBSCRIPTION: "CREATE_SUBSCRIPTION",
    GET_PRODUCTS: "GET_PRODUCTS",
    FINALIZE_SALE: "FINALIZE_SALE",
    CREATE_CONTRACT: "CREATE_CONTRACT",
    EMAIL_WELCOME: "EMAIL_WELCOME",
    FIND_PERSON: "FIND_PERSON",
    CREATE_OTP: "CREATE_OTP",
    CHECK_OTP: "CHECK_OTP",
    SALE_REGISTER: "SALE_REGISTER",
    ERROR_REGISTER: "ERROR_REGISTER"
}